import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'

import { cn } from '@/lib/utils'
import { UserSessionProvider } from '@/context/user_session_context'
import { Toaster } from '@/components/ui/toaster'

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Kart-TI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <UserSessionProvider>
      <html lang="pt-br" style={{ scrollbarWidth: 'none' }}>
        <body
          className={cn(
            'flex flex-col w-full min-h-screen bg-background font-sans antialiased',
            fontSans.variable,
          )}
        >
          {children}
          <Toaster />
        </body>
      </html>
    </UserSessionProvider>
  )
}
